// <auto-generated />
using Labb_2___LINQ.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb_2___LINQ.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20220306192142_Updated")]
    partial class Updated
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Labb_2___LINQ.Models.Class", b =>
                {
                    b.Property<int>("ClassID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassID"), 1L, 1);

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseClassID")
                        .HasColumnType("int");

                    b.Property<int>("TeacherClassesTeacherClassID")
                        .HasColumnType("int");

                    b.HasKey("ClassID");

                    b.HasIndex("CourseClassID");

                    b.HasIndex("TeacherClassesTeacherClassID");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Labb_2___LINQ.Models.Course", b =>
                {
                    b.Property<int>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseID"), 1L, 1);

                    b.Property<int>("CourseClassID")
                        .HasColumnType("int");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeacherID")
                        .HasColumnType("int");

                    b.HasKey("CourseID");

                    b.HasIndex("CourseClassID");

                    b.HasIndex("TeacherID");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Labb_2___LINQ.Models.CourseClass", b =>
                {
                    b.Property<int>("CourseClassID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseClassID"), 1L, 1);

                    b.HasKey("CourseClassID");

                    b.ToTable("CourseClasses");
                });

            modelBuilder.Entity("Labb_2___LINQ.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"), 1L, 1);

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<string>("StudentEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentID");

                    b.HasIndex("CourseID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Labb_2___LINQ.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherID"), 1L, 1);

                    b.Property<string>("TeacherEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeacherID");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("Labb_2___LINQ.Models.TeacherClass", b =>
                {
                    b.Property<int>("TeacherClassID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherClassID"), 1L, 1);

                    b.HasKey("TeacherClassID");

                    b.ToTable("TeacherClasses");
                });

            modelBuilder.Entity("TeacherTeacherClass", b =>
                {
                    b.Property<int>("TeacherClassesTeacherClassID")
                        .HasColumnType("int");

                    b.Property<int>("TeachersTeacherID")
                        .HasColumnType("int");

                    b.HasKey("TeacherClassesTeacherClassID", "TeachersTeacherID");

                    b.HasIndex("TeachersTeacherID");

                    b.ToTable("TeacherTeacherClass");
                });

            modelBuilder.Entity("Labb_2___LINQ.Models.Class", b =>
                {
                    b.HasOne("Labb_2___LINQ.Models.CourseClass", "CourseClass")
                        .WithMany("Classes")
                        .HasForeignKey("CourseClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb_2___LINQ.Models.TeacherClass", "TeacherClasses")
                        .WithMany("Classes")
                        .HasForeignKey("TeacherClassesTeacherClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseClass");

                    b.Navigation("TeacherClasses");
                });

            modelBuilder.Entity("Labb_2___LINQ.Models.Course", b =>
                {
                    b.HasOne("Labb_2___LINQ.Models.CourseClass", "CourseClass")
                        .WithMany("Courses")
                        .HasForeignKey("CourseClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb_2___LINQ.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseClass");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Labb_2___LINQ.Models.Student", b =>
                {
                    b.HasOne("Labb_2___LINQ.Models.Course", "Course")
                        .WithMany("Student")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("TeacherTeacherClass", b =>
                {
                    b.HasOne("Labb_2___LINQ.Models.TeacherClass", null)
                        .WithMany()
                        .HasForeignKey("TeacherClassesTeacherClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb_2___LINQ.Models.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeachersTeacherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Labb_2___LINQ.Models.Course", b =>
                {
                    b.Navigation("Student");
                });

            modelBuilder.Entity("Labb_2___LINQ.Models.CourseClass", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Courses");
                });

            modelBuilder.Entity("Labb_2___LINQ.Models.TeacherClass", b =>
                {
                    b.Navigation("Classes");
                });
#pragma warning restore 612, 618
        }
    }
}
